# Site settings
title: zaitra.io
email: info@zaitra.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description. (TODO)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Zaitra s.r.o.
email: info@zaitra.io
facebook_username: zaitra.io
twitter_username: zaitra.io
github_username: zaitra.io
address:  
  - line: Technick√° 23
  - line: Brno, Czech Republic
  # Feel free to add more lines here 
telephone: +421 944 244 120
copyright: Zaitra s.r.o.

# Build settings
markdown: kramdown